### PR TITLE
use `template` as the context node

### LINKED ISSUE #2: Using a `template` context element
As mentioned in https://github.com/sparklemotion/nokogiri/issues/3023#issuecomment-2076077730, I tested parsing using a `template` as the context node in all cases. This does not work when the fragment contains a `head` or `body` tag but appears to work in every other case.

Specifically, after
```diff
diff --git a/lib/nokogiri/html5/inference.rb b/lib/nokogiri/html5/inference.rb
index e501e01..942089d 100644
--- a/lib/nokogiri/html5/inference.rb
+++ b/lib/nokogiri/html5/inference.rb
@@ -132,12 +132,7 @@ else
             if context.nil?
               Nokogiri::HTML5::Document.parse(input)
             else
-              fragment = Nokogiri::HTML5::DocumentFragment.new(Nokogiri::HTML5::Document.new, input, context)
-              if pluck && (path = pluck_path(input))
-                fragment.xpath(path)
-              else
-                fragment
-              end
+              Nokogiri::HTML5::DocumentFragment.new(Nokogiri::HTML5::Document.new, input, 'template')
             end
           end
```
all of the tests pass except for 3: 
```
Run options: --seed 37366

# Running:

...........FFF.............

Finished in 0.013474s, 2003.8593 runs/s, 3562.4165 assertions/s.

  1) Failure:
Nokogiri::HTML5::Inference::.parse::passed a fragment requiring 'in html' insertion mode#test_0001_parses '<body><div>hello</div></body>' correctly [test/nokogiri/html5/test_inference.rb:96]:
--- expected
+++ actual
@@ -1 +1 @@
-"<body><div>hello</div></body>"
+"<div>hello</div>"


  2) Failure:
Nokogiri::HTML5::Inference::.parse::passed a fragment requiring 'in html' insertion mode#test_0002_parses '<head><meta charset="UTF-8"><title>hello</title></head>' correctly [test/nokogiri/html5/test_inference.rb:96]:
--- expected
+++ actual
@@ -1 +1 @@
-"<head><meta charset=\"UTF-8\"><title>hello</title></head>"
+"<meta charset=\"UTF-8\"><title>hello</title>"


  3) Failure:
Nokogiri::HTML5::Inference::.parse::multiple children that need plucking::with pluck: false#test_0001_includes the intermediate nodes created [test/nokogiri/html5/test_inference.rb:116]:
--- expected
+++ actual
@@ -1 +1 @@
-"<tbody><tr><td>hello</td></tr><tr><td>world</td></tr></tbody>"
+"<tr><td>hello</td></tr><tr><td>world</td></tr>"


27 runs, 48 assertions, 3 failures, 0 errors, 0 skips
```

Unfortunately, parsing a fragment containing a `head` element in the context of `html` also produces an empty `body` element. Similarly, parsing a fragment containing a `body` element in the context of `html` also produces an empty `head`.

This behavior actually exposes a bug in the current implementation of `Inference::parse`. These tests should pass, but they fail.
```diff
diff --git a/test/nokogiri/html5/test_inference.rb b/test/nokogiri/html5/test_inference.rb
index 2f00898..2fd9e4f 100644
--- a/test/nokogiri/html5/test_inference.rb
+++ b/test/nokogiri/html5/test_inference.rb
@@ -99,6 +99,25 @@ describe Nokogiri::HTML5::Inference do
       end
     end

+    describe "passed a Fragment containing head and body" do
+      it "returns a Fragment containing both head and body" do
+        fragment = "<head></head><body></body>"
+        actual = Nokogiri::HTML5::Inference.parse(fragment).to_html
+
+        assert_equal(fragment, actual)
+      end
+    end
+
+    describe "passed a Fragment containing head and p" do
+      it "returns a Fragment containing both head and body" do
+        fragment = "<head><p>"
+        expected = "<head></head><body><p></p></body>"
+        actual = Nokogiri::HTML5::Inference.parse(fragment).to_html
+
+        assert_equal(expected, actual)
+      end
+    end
+
     describe "multiple children that need plucking" do
       it "parses correctly" do
         fragment = "<tr><td>hello</td></tr><tr><td>world</td></tr>"
```

My inclination is to say that this is a bug in the HTML standard which should allow `head` and `body` elements to appear inside a `template`. A quick test shows that Firefox follows the standard as written and disallows that.

### PR DESCRIPTION
**Pull request by flavorjones**
which simplifies the code quite a bit

Closes #2

cc @stevecheckoway

### CODE REVIEW

**Comment by marcoroth** [comment]
Oh I see, this is a neat trick!

**Comment by flavorjones** [comment]
Updated the branch to include changing the README's description of what's going on.

**Comment by flavorjones** [comment]
@marcoroth Let me know if this branch still works OK with StimulusReflex and if so we can merge it!

**Comment by marcoroth** [comment]
Looks almost good, I got a few weird failing tests like this one related to `#inner_html`:
```ruby
  test "should properly parse <td>" do
    html = "<td>1</td>"
    fragment = StimulusReflex::HTML::DocumentFragment.new(html)

    assert_equal "<td>1</td>", fragment.to_html.squish
    assert_equal "<td>1</td>", fragment.outer_html.squish
    assert_equal "1", fragment.inner_html.squish
  end
```

The last assertion is falling with:

```ruby
Expected: "1"
Actual: "<td>1</td>"
```

**Comment by flavorjones** [comment]
@marcoroth That's strange:

```ruby
Nokogiri::HTML5::DocumentFragment.new(
  Nokogiri::HTML5::Document.new,
  "<td>foo</td>",
  "template"
).to_html
# => "<td>foo</td>"
```

Is there something going on in SR that is adding a `th` tag?

**Comment by marcoroth** [comment]
It seems like it's something in SR, trying to figure out what's up 🤔

**Comment by marcoroth** [comment]
Okay my bad, I just looked at the wrong test output. The `<th>` came from a different test.

I see this though:
```ruby
nokogiri-html5-inference on main via v3.3.0
❯ bundle console
irb(main):001> Nokogiri::HTML5::Inference.parse(%(<td>1</td>)).inner_html
=> "1"
```

```ruby
nokogiri-html5-inference on 2-use-template-context-node via v3.3.0
❯ bundle console
irb(main):001> Nokogiri::HTML5::Inference.parse(%(<td>1</td>)).inner_html
=> "<td>1</td>"
```

**Comment by stevecheckoway** [comment]
What behavior are you expecting for inner_html on a document fragment?

I took a quick look at what interfaces the DOM standard says a DocumentFragment should support and none mentioned inner_html which is defined for Elements.

My intuition is that Nokogiri's behavior here is reasonable.

**Comment by marcoroth** [comment]
Yeah, I think the behavior for inner_html on a `Nokogiri::HTML5::DocumentFragment` is fine as-is. The difference here is that the `Nokogiri::HTML5::Inference.parse` method previously returned a `Nokogiri::XML::NodeSet` which has a different behavior for inner_html.

**Comment by flavorjones** [comment]
@marcoroth :thinking: We could change the code to always return a NodeSet instead of a DocumentFragment, if that would be helpful? It would just involve returning `fragment.children`.

(After thinking about this for a minute, I think I _slightly_ prefer this because DocumentFragment's behavior is very ad-hoc and my plan is to eventually make it a subclass of NodeSet, see sparklemotion/nokogiri#2184.)

**Comment by flavorjones** [comment]
I'm going to merge this, and then create a new PR that always returns a NodeSet so we can evaluate that decision separately.

**Comment by flavorjones** [comment]
See #8

**Pull request merged**
